services:
  psql:
    image: postgres:14-alpine3.20
    environment:
      POSTGRES_DB: file-info
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
#    ports: [ 5444:5432 ]

  file-service:
    container_name: file-service
    build:
      context: .
    ports: [ 8080:8080 ]
    entrypoint: [ "/app/wait-for.sh", "psql:5432", "--", "/app/start.sh" ]
    command: [ "java", "-jar", "/app/app.jar", "--spring.config.location=file:/app/configs.yaml" ]
    depends_on: [ "psql" ]
    volumes: [ "~/files:/files"]