server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5444/file-info'
    username: root
    password: root
    driver-class-name: 'org.postgresql.Driver'

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true

file-system:
  storage_dir: "/home/khalid/Desktop/java-projects/FileService/files/"
